### ISSUE TITLE
rubocop-rspec

### ISSUE THREAD

**Issue by geniou** [lelylan/betterspecs#109]
[rubocop-rspec](https://github.com/nevir/rubocop-rspec) (an extension to [rubocop](https://github.com/bbatsov/rubocop)) is a tool to check the code style of RSpec files. Maybe you can promote it somewhere on the betterspecs.org page?

Some of the rules of betterspecs.org are already in there, like: "Use let and let!", "Do not use should" or checks for the file name, or to enforce the use of `described_class`.

If you have new ideas what could be checked with this tool let me know.

**Comment by onebree** [comment]
@geniou Feel free to submit a PR promoting this gem. Rubocop is great and features support for the famous Community Ruby Style Guide.

I have not checked your source code, but it would be good to add support for using other DSL from gems like Capybara. The app I contribute to for work does integration testing with `background`, `scenario`, `feature` keywords.
