### ISSUE TITLE
Update roadmap, seeking collaborators!

### ISSUE THREAD

**Issue by onebree** [lelylan/betterspecs#146]
In the past few weeks, betterspecs has gained some new collaborators to the repository. While everyone on the team is enthusiastic, we have huge plans and need some additional help!

For complete transparency, here is an unordered list of things we would like to accomplish:

- Obtain more collaborators, especially those who can help monitor translations
- Convert the website (now hosted on Heroku) to a Github Page powered by Jekyll (#153)
- Develop a versioning style, and apply it to all translations. EN would be the most current, with all translations attempting to follow.
  + Possibly moving each translation to its own branch or directory within the repository.
  + We want to use version numbers on the individual translations, we we believe it will help keep them in sync with EN (#20, #78)
- Create a blog and newsletter for website and repository updates
- Also see issue #144 

Feel free to leave comments on any ideas you may have.

If you are interested in becoming a collaborator, please email @andreareginato (see profile), as he is the owner of this repository.

**Comment by akz92** [comment]
Hi, I'm here to help. I emailed Andrea last week but haven't got an answer yet. In the mean time I started to transfer the site to Jekyll, it's hosted on my GH Pages: http://akz92.github.io

**Comment by benoittgt** [comment]
Happy to help for french translation and more like `Possibly moving each translation to its own branch or directory within the repository.`

**Comment by onebree** [comment]
@akz92 and @benoittgt Great to hear that you guys want to help! I have not heard from Andrea in over a month. Unfortunately, I have stopped focusing on helping out, because of the lack of communication....So nothing has been officially done or even worked on.

**Comment by andreareginato** [comment]
Hi everyone. My apologies with @onebree and all the people willing to make betterspecs a better project. 

Right now I've no time to dedicate to the project (due to other priorities) and what I need is to have a team of people that can independently take the decisions to improve the project. What I can do form my side is to check the plan definition and then place the new website when complete.

I know it's not an easy task but right now this is what I can do.
Thanks everyone

**Comment by onebree** [comment]
@andrea Would it be best to transfer ownership of the project? It seems like someone has recreated the entire site to be hosted on Github Pages, rather than heroku. This completes one part of the plan we discussed in Slack

**Comment by andreareginato** [comment]
Hi Hunter,

the project it self is both for the community and personal portfolio. For
me the best option would be to keep the repo the one we are using, with
total freedom for collaborators to fork and merge new solutions.

On Sun, Aug 30, 2015 at 3:59 PM, Hunter Stevens <notifications@github.com>
wrote:

> @andrea <https://github.com/andrea> Would it be best to transfer
> ownership of the project? It seems like someone has recreated the entire
> site to be hosted on Github Pages, rather than heroku. This completes one
> part of the plan we discussed in Slack
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andreareginato/betterspecs/issues/146#issuecomment-136139860>
> .
>



-- 
Andrea Reginato
Lelylan | reThink your house
http://lelylan.com

**Comment by akz92** [comment]
I don't mind keeping the project where it is. The Jekyll version is finished so if you want to use it I can make a pull request.

**Comment by andreareginato** [comment]
Wow. Sounds great.
Can you first deploy it as beta so that I can check it out.

Thanks a lot.

On Tue, Sep 29, 2015 at 1:33 PM, Lucas A. Moulin <notifications@github.com>
wrote:

> I don't mind keeping the project where it is. The Jekyll version is
> finished so if you want to use it I can make a pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andreareginato/betterspecs/issues/146#issuecomment-144032419>
> .
>



-- 
Andrea Reginato
Lelylan | reThink your house
http://lelylan.com

**Comment by akz92** [comment]
@andreareginato I don't know if this is what you are talking about, but it's already running on my github pages: http://akz.me

**Comment by andreareginato** [comment]
Exactly that. I can see some missing sections.
Once we overcome to them (e.g. screencasts, social buttons) and have a
solid new version we can make the merge.



On Tue, Sep 29, 2015 at 1:48 PM, Lucas A. Moulin <notifications@github.com>
wrote:

> @andreareginato <https://github.com/andreareginato> I don't know if this
> is what you are talking about, but it's already running on my github pages:
> http://akz.me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andreareginato/betterspecs/issues/146#issuecomment-144035393>
> .
>



-- 
Andrea Reginato
Lelylan | reThink your house
http://lelylan.com

**Comment by akz92** [comment]
Ok, I'll work on that on the weekend and I'll let you know when It's ready.

**Comment by onebree** [comment]
@andreareginato  I understand why you want to keep yourself as the repo's owner.

@akz92 syntax highlighting in Jekyll is easy. It does not look pretty when viewing the markdown on Github, but is nice on the site itself.

```
{% highlight ruby %}
def some_method
  puts 'hello!'
end
{% endhighlight %}
```

**Comment by akz92** [comment]
@onebree nice I'll try that later. If you or anyone else want to help me it'll be great I can give you permission to edit the repo directly.

**Comment by onebree** [comment]
I have experience with Jekyll for my github blog. The original idea was for me to monitor edits to the jekyll page, but not create it entirely. (I am not much of a front-end person. I can design but have no patience for CSS.)

**Comment by onebree** [comment]
@akz92 Hello there. Any update on the website? I do not think I am a collaborator with permissions to help. Instead, I will just submit pull requests. Again, thank you for taking the time to recreate the whole site!

**Comment by andreareginato** [comment]
I guess it's still work in progress. Hunter, actually you have full
permissions for the repo.
All the best.

**Comment by akz92** [comment]
@onebree Hi. I haven't been able to finish the port, I'll give you both collaborator permission but feel free to fork it and use the code any way you want.

**Comment by onebree** [comment]
@akz92 I will fork your project and submit pull requests for any changes I make. That way, rollbacks are easier if necessary

**Comment by onebree** [comment]
@andreareginato and @akz92 for further discussion on the website, please see issue #153

**Comment by onebree** [comment]
Should I close this issue? We can make a blurb in README that explains "If you want to become a maintainer, especially for translations, please contact one of our admins..."

**Comment by benoittgt** [comment]
I'm ok to close this one.
