### ISSUE TITLE
Use an i18n tool to maintain translations

### ISSUE THREAD

**Issue by onebree** [lelylan/betterspecs#167]
Originated from https://github.com/lelylan/betterspecs/issues/153#issuecomment-182799572

- [x] Use [jekyll-multiple-languages-plugin][1] to maintain translations

@akz92 -- please coordinate with @benoittgt, as he will be moving the translated pages to the new layout.

[1]: https://github.com/screeninteraction/jekyll-multiple-languages-plugin

**Comment by akz92** [comment]
@onebree ok, I'll start this task tonight.
@benoittgt I believe it's better to wait for the i18n translation before moving the pages to the new layout, because once the translation is finished there will be only one page to move.

**Comment by vtorves** [comment]
Hi, @akz92 
hi, I can help with translations?

**Comment by benoittgt** [comment]
Ok @akz92 !

**Comment by akz92** [comment]
Sure @vtorves. I'm still looking for the best approach, apparently i18n translation in Jekyll isn't as simple as it's in Rails. Maybe you could help me find good active gems to use or some examples/documentations.

**Comment by vtorves** [comment]
@akz92 rails really is very simple! I solved the translation using https://github.com/untra/polyglot . 
how you prefer that i share my tests? branch? gist? here?

**Comment by akz92** [comment]
@vtorves please commit it to a new brach.

**Comment by onebree** [comment]
@vtorves as mentioned above, for any contributions, please do the following:

1. Fork this repository and fetch all branches
2. Checkout `gh-pages` then `git checkout -b name-of-feature`

**Comment by akz92** [comment]
@vtorves can you share what you did? I didn't have the time to study other solutions, it would be great to see how you solved it.

**Comment by vtorves** [comment]
@onebree thanks!! =)
@akz92 of course ! yes I can. I will adjust better the flow and charge here tomorrow.
