### ISSUE TITLE
Homepage stored in GitHub metadata is not a URL

### ISSUE THREAD

**Issue by david-a-wheeler** [lelylan/betterspecs#180]
The homepage stored by GitHub is "betterspecs.org" - but that isn't a URL.  You can see this by viewing: https://api.github.com/repos/lelylan/betterspecs .  Systems have to guess if this is https:// or http:// URL ... in this case, it's http.

Would an owner please look near the top where it says "RSpec Best Practices http://betterspecs.org", and click on "edit"?  Then modify the homepage to say:
http://betterspecs.org

Thanks!

**Comment by akz92** [comment]
Thanks @david-a-wheeler! Fixed it.

**Comment by onebree** [comment]
@akz92 please link to the commit/PR that closed this issue :-)

**Comment by akz92** [comment]
@onebree the isn't a commit/PR related to this issue, it's just an edit to our Github description
